// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdakkqzpcwarahrmllop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkYWtrcXpwY3dhcmFocm1sbG9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyODkzNDIsImV4cCI6MjA2Mjg2NTM0Mn0.TV1LApKCR0o32wkHzxVwTDL8ktPLSfUM_wlNdZnVkaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);